FROM ubuntu:18.04
MAINTAINER ScriptMaster <msheriffusa@gmail.com>

# ENV ANDROID_SDK_URL="https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip" \ 
RUN apt update && apt install -y android-sdk android-sdk-platform-23

